site_name: Designing Data Intesive Application Notes

theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - python
nav:
    - Home: index.md
    - Chapter 1: chapter1.md
    - Chapter 2: chapter2.md
    - Chapter 3: chapter5.md