site_name: Designing Data Intesive Application Notes

theme:
    name: material
nav:
    - Introduction: index.md
    - Chapter 1: chapter1.md
    - Chapter 2 Data Models: chapter2.md
    - Chapter 5 Replication: chapter5.md
